### ISSUE TITLE
Python: Exploring GitHub Codespaces as an alternative dev environment

### ISSUE THREAD

**Issue by j4ckofalltrades** [SheCodesAustralia/workshopcontent#29]
*Request for feedback / suggestions*

From a previous one day workshop I mentored at, there were a couple of participants that had their work laptops with them which meant they couldn't install the required software for the lesson. I looked into [GitHub Codespaces](https://github.com/features/codespaces) as a solution to this problem.

Codespaces allows us to spin up a pre-configured dev environment in the cloud and connect to it via a web browser using [Visual Studio Code for the Web](https://code.visualstudio.com/docs/editor/vscode-web), this means that participants only need 1.) a GitHub account and 2.) a web browser to be able to use codespaces (GitHub provides up to 60 hours of free usage per month).

I did a quick proof-of-concept template repository at https://github.com/j4ckofalltrades/codespaces-python-gui that can be opened up in a codespace; this has Python 3 pre-configured as well as a lightweight-desktop environment (we need a GUI for the  Space Turtle Chomp game).

Here it is in action:

https://github.com/SheCodesAustralia/workshopcontent/assets/1442368/b89db8cb-da31-42e8-b0a7-4b626e08b68c

Side note: I skipped the provisioning part in the recording above, it takes around ~3 minutes to build and provision the dev environment.

I was thinking we could add a separate section in the [Python Installation lesson](https://tutorials.shecodes.com.au/python/getting_started/1_python_installation/) for the scenario above (if Codespaces proves to be a viable option).

**Comment by Hauteclere** [comment]
This is an awesome suggestion! I think we absolutely should make use of this technique in our one-day workshops, because it massively simplifies the install process and means that we can standardise the terminal commands between Mac and Windows. 

The plan is to launch a complete overhaul of the one day content in the semi-near future, but I'm not quite up to that point yet. First I need to finalise the Plus content, the mentor onboarding materials, and the student handbook.   When I do begin, having seen this I think I'll pursue making Github Codespaces the preferred way of working. Would you be happy for me to use your template repo as a jumping-off point, and credit you?

**Comment by j4ckofalltrades** [comment]
@Hauteclere

> Would you be happy for me to use your template repo as a jumping-off point, and credit you?

Yes, feel free to use it.
